import React from 'react';
import Head from 'next/head';
import styles from '../styles/Layout.module.css';
import Header from './header';
import useAntDesign from '../hooks/useAntDesign';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const { AntdLayout, Content, Footer } = useAntDesign();

  return (
    <>
      <Head>
        <title>AWESOME FOOD STORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AntdLayout className="container">
        <Header />
        <Content className={styles.content}>
          <section className={styles.section}>{children}</section>
        </Content>
        <Footer>@ 2018 purpleworks</Footer>
      </AntdLayout>
    </>
  );
};

export default Layout;
