import React from 'react';
import Head from 'next/head';
import { Layout as AntdLayout } from 'antd';
import Header from './Header';

const { Content, Footer } = AntdLayout;

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>AWESOME FOOD STORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AntdLayout className="container">
        <Header />
        <Content>{children}</Content>
        <Footer>@ 2018 purpleworks</Footer>
      </AntdLayout>
    </>
  );
};

export default Layout;
